let indianNames = [
  "Aarav",
  "Aarushi",
  "Abhay",
  "Aditi",
  "Advik",
  "Aishwarya",
  "Akash",
  "Akshara",
  "Amit",
  "Amrita",
  "Ananya",
  "Aniket",
  "Anjali",
  "Ankit",
  "Anushka",
  "Arjun",
  "Arpita",
  "Arun",
  "Asha",
  "Ashish",
  "Ayush",
  "Bhagyashree",
  "Bhavesh",
  "Chaitanya",
  "Chandni",
  "Darshan",
  "Deepak",
  "Dhruv",
  "Divya",
  "Esha",
  "Gaurav",
  "Gayatri",
  "Harsh",
  "Heena",
  "Himanshu",
  "Ishaan",
  "Jagruti",
  "Jatin",
  "Jaya",
  "Kabir",
  "Kajal",
  "Karan",
  "Karishma",
  "Kartik",
  "Kavya",
  "Kiran",
  "Krish",
  "Krishna",
  "Lakshmi",
  "Madhav",
  "Mahesh",
  "Manisha",
  "Mayank",
  "Meera",
  "Mihir",
  "Mitali",
  "Mohan",
  "Mohini",
  "Neha",
  "Nikhil",
  "Nisha",
  "Nitin",
  "Pooja",
  "Pranav",
  "Prerna",
  "Rahul",
  "Raj",
  "Rajesh",
  "Rakesh",
  "Rhea",
  "Rishi",
  "Riya",
  "Ronak",
  "Ruchi",
  "Rohan",
  "Roshni",
  "Rupal",
  "Sahil",
  "Sanjay",
  "Sapna",
  "Sarita",
  "Shiv",
  "Shreya",
  "Siddharth",
  "Simran",
  "Sneha",
  "Sohan",
  "Sonali",
  "Sudhir",
  "Suhana",
  "Suman",
  "Sushant",
  "Tanvi",
  "Tarun",
  "Trisha",
  "Uday",
  "Uma",
  "Varun",
  "Vidya",
  "Vikas",
];

export function generateRandomName() {
  return indianNames[Math.floor(Math.random() * indianNames.length)];
}

const messages = [
  "Wow, that's amazing!",
  "I totally agree with you.",
  "What a cool video!",
  "Can't stop watching this!",
  "This is so helpful, thanks!",
  "Anybody else here from [specific reference]?",
  "I've been looking for this information everywhere.",
  "Great job, keep it up!",
  "I'm learning so much from this channel.",
  "Does anyone know where I can find more content like this?",
  "Hey everyone!",
  "This is my first time here, loving it so far!",
  "That's hilarious 😂",
  "I'm a huge fan of [content creator/channel]!",
  "This video changed my perspective.",
  "I wish I found this sooner.",
  "I'm from [location], anyone else?",
  "This deserves more views!",
  "I've been binge-watching your videos all day!",
  "Can you make a video about [topic] next?",
  "This made my day!",
  "I'm sharing this with all my friends.",
  "I'm so inspired right now.",
  "Is it just me or is this addicting?",
  "I can't get enough of this content!",
  "I never knew I needed this until now.",
  "Thank you for creating this!",
  "I have a question about [topic], can someone help me?",
  "This channel is underrated.",
  "This content is gold!",
];

// Function to generate random messages
export function generateRandomMessage() {
  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
}
